test

diff --git a/.github/workflows/benchmarks.yml b/.github/workflows/benchmarks.yml
--- a/.github/workflows/benchmarks.yml
+++ b/.github/workflows/benchmarks.yml
@@ -90,8 +90,23 @@ jobs:
       - name: Run benchmarks for last 4 commits if not PR
         if: github.event_name != 'pull_request'
         run: |
-          git log -n 4  --pretty=format:"%H" >> tag_commits.txt
-          asv run -a rounds=1 HASHFILE:tag_commits.txt | tee asv-output.log
+          # Get last 4 commit hashes
+          git log -n 4 --pretty=format:"%H" > tag_commits.txt
+          
+          # Benchmark each commit using existing environment
+          while read commit_hash; do
+            echo "Benchmarking commit: $commit_hash"
+            git checkout $commit_hash
+            pip install -e ".[tardisbase]"
+            pip install --no-deps qgridnext lineid_plot
+            TARDIS_REF_PATH=tardis-regression-data/atom_data asv dev --set-commit-hash $commit_hash -a rounds=1
+          done < tag_commits.txt | tee asv-output.log
+          
+          # Return to original state
+          git checkout HEAD
+          pip install -e ".[tardisbase]"
+          pip install --no-deps qgridnext lineid_plot
+          
           if grep -q failed asv-output.log; then 
             echo "Some benchmarks have failed!"
             exit 1
@@ -100,10 +115,6 @@ jobs:
       - name: Generate Graphs and HTML
         if: github.event_name != 'pull_request'
         run: asv publish
-
-      - name: Delete env files
-        if: github.event_name != 'pull_request'
-        run: rm -r .asv/env
 
       - name: Deploy asv page
         if: github.event_name != 'pull_request'
@@ -120,19 +131,42 @@ jobs:
       - name: Run benchmarks for base and head commits of PR
         if: github.event_name == 'pull_request'
         run: |
-          echo $(git rev-parse HEAD) > commit_hashes.txt
-          echo $(git rev-parse master) >> commit_hashes.txt
-          asv run -a rounds=1 HASHFILE:commit_hashes.txt -E existing:/home/runner/micromamba/envs/tardis/bin/python | tee asv-output-PR.log  
-            if grep -q failed asv-output-PR.log; then 
-              echo "Some benchmarks have failed!"
-              exit 1
-            fi
+          # Get commit hashes
+          HEAD_HASH=$(git rev-parse HEAD)
+          MASTER_HASH=$(git rev-parse master)
+          
+          # Benchmark master branch
+          echo "Benchmarking master commit: $MASTER_HASH"
+          git checkout master
+          pip install -e ".[tardisbase]"
+          pip install --no-deps qgridnext lineid_plot
+          TARDIS_REF_PATH=tardis-regression-data/atom_data asv dev --set-commit-hash $MASTER_HASH -a rounds=1
+          
+          # Benchmark PR head
+          echo "Benchmarking PR head commit: $HEAD_HASH"
+          git checkout $HEAD_HASH
+          pip install -e ".[tardisbase]"
+          pip install --no-deps qgridnext lineid_plot
+          TARDIS_REF_PATH=tardis-regression-data/atom_data asv dev --set-commit-hash $HEAD_HASH -a rounds=1 | tee asv-output-PR.log
+          
+          if grep -q failed asv-output-PR.log; then 
+            echo "Some benchmarks have failed!"
+            exit 1
+          fi
 
       - name: Compare Master and PR head
-        run: asv compare origin/master HEAD --factor 1.1 --split --sort ratio | tee asv-compare-output.log
+        if: github.event_name == 'pull_request'
+        run: |
+          HEAD_HASH=$(git rev-parse HEAD)
+          MASTER_HASH=$(git rev-parse master)
+          asv compare $MASTER_HASH $HEAD_HASH --factor 1.1 --split --sort ratio | tee asv-compare-output.log
 
       - name: Compare Master and PR head but only show changed results
-        run: asv compare origin/master HEAD --only-changed --factor 1.1 --split --sort ratio | tee asv-compare-changed-output.log
+        if: github.event_name == 'pull_request'
+        run: |
+          HEAD_HASH=$(git rev-parse HEAD)
+          MASTER_HASH=$(git rev-parse master)
+          asv compare $MASTER_HASH $HEAD_HASH --only-changed --factor 1.1 --split --sort ratio | tee asv-compare-changed-output.log
 
       - name: Benchmarks compare output
         id: asv_pr_vs_master
@@ -150,10 +184,6 @@ jobs:
         if: github.event_name == 'pull_request'
         run: |
           asv publish
-
-      - name: Delete env files of PR
-        if: github.event_name == 'pull_request'
-        run: rm -r .asv/env
 
       - name: Set destination directory
         if: github.event_name == 'pull_request'
