Refactor benchmarks (#2722)
* fix base commit hash of PR in benchmark action

Signed-off-by: Asish Kumar <officialasishkumar@gmail.com>

* remove unused variables

Signed-off-by: Asish Kumar <officialasishkumar@gmail.com>

* refactor benchmarks

Signed-off-by: Asish Kumar <officialasishkumar@gmail.com>

* change file name

Signed-off-by: Asish Kumar <officialasishkumar@gmail.com>

* remove parameters

Signed-off-by: Asish Kumar <officialasishkumar@gmail.com>

* remove some steps from benchmarks

Signed-off-by: Asish Kumar <officialasishkumar@gmail.com>

* delay of 2 sec

Signed-off-by: Asish Kumar <officialasishkumar@gmail.com>

* some changes that needs to be reverted

Signed-off-by: Asish Kumar <officialasishkumar@gmail.com>

* fix benchmark

Signed-off-by: Asish Kumar <officialasishkumar@gmail.com>

* fix the commit hash

Signed-off-by: Asish Kumar <officialasishkumar@gmail.com>

* remove testing statements

Signed-off-by: Asish Kumar <officialasishkumar@gmail.com>

---------

Signed-off-by: Asish Kumar <officialasishkumar@gmail.com>

diff --git a/.github/workflows/benchmarks.yml b/.github/workflows/benchmarks.yml
--- a/.github/workflows/benchmarks.yml
+++ b/.github/workflows/benchmarks.yml
@@ -98,15 +98,23 @@ jobs:
           user_name: "TARDIS Bot"
           user_email: "tardis.sn.bot@gmail.com"
 
-      - name: Run benchmarks
+      - name: Run benchmarks for base and head commits of PR
         if: github.event_name == 'pull_request_target'
-        run: asv run --config asv.conf.json
+        run: |
+          echo ${{ github.event.pull_request.base.sha }} > commit_hashes.txt
+          echo ${{ github.event.pull_request.head.sha }} >> commit_hashes.txt
+
+          asv run -a repeat=2 -a rounds=1 HASHFILE:commit_hashes.txt | tee asv-output-PR.log  
+            if grep -q failed asv-output-PR.log; then 
+              echo "Some benchmarks have failed!"
+              exit 1
+            fi
 
       - name: Compare Master and PR head
-        run: asv compare origin/master HEAD --config asv.conf.json | tee asv-compare-output.log
+        run: asv compare ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} --config asv.conf.json | tee asv-compare-output.log
 
       - name: Compare Master and PR head but only show changed results
-        run: asv compare origin/master HEAD --only-changed --config asv.conf.json | tee asv-compare-changed-output.log
+        run: asv compare ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} --only-changed --config asv.conf.json | tee asv-compare-changed-output.log
 
       - name: Benchmarks compare output
         id: asv_pr_vs_master
@@ -119,18 +127,6 @@ jobs:
         uses: juliangruber/read-file-action@v1.0.0
         with:
           path: asv-compare-changed-output.log
-
-      - name: Run benchmarks for base to head commits of PR
-        if: github.event_name == 'pull_request_target'
-        run: |
-          echo $(git rev-parse HEAD) > commit_hashes.txt
-          echo $(git merge-base HEAD upstream/master) >> commit_hashes.txt
-
-          asv run -a repeat=1 -a rounds=1 HASHFILE:commit_hashes.txt | tee asv-output-PR.log  
-            if grep -q failed asv-output-PR.log; then 
-              echo "Some benchmarks have failed!"
-              exit 1
-            fi
 
       - name: Generate Graphs and HTML of PR
         if: github.event_name == 'pull_request_target'
